name: "technology_config"
description: "This plant has wind feeding into an electrolyzer with optimization"

technologies:
  hybrid:
    performance_model:
      model: "hybrid"
      config: !include tech_inputs/hopp_config.yaml
    cost_model:
      model: "hybrid"
    financial_model:
      group: "profast"
