name: "technology_config"
description: "This plant has wind feeding into an electrolyzer with optimization"

technologies:
  hopp:
    performance_model:
      model: "hopp"
      config: !include tech_inputs/hopp_config.yaml
    cost_model:
      model: "hopp"
    financial_model:
      group: "profast"
